// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2X6dHf8QrfNURNvZ4tYeHpTzf5K6wy-0',
    appId: '1:140355243144:android:a6ac1f14183172f272633d',
    messagingSenderId: '140355243144',
    projectId: 'diogoprojects-617e2',
    databaseURL: 'https://diogoprojects-617e2.firebaseio.com',
    storageBucket: 'diogoprojects-617e2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnSRKhrYvK6y9CNtgFJFWimT3QTHjfHFI',
    appId: '1:140355243144:ios:08ceded889bb563c72633d',
    messagingSenderId: '140355243144',
    projectId: 'diogoprojects-617e2',
    databaseURL: 'https://diogoprojects-617e2.firebaseio.com',
    storageBucket: 'diogoprojects-617e2.appspot.com',
    androidClientId: '140355243144-3om8sko8uaiiaouqg77ejqih4347aras.apps.googleusercontent.com',
    iosBundleId: 'com.housemira.app',
  );
}
