"""Generates the feature dependency graph (ADR-0006).

Run locally: python3 tool/generate_dependency_graph.py [--write]
  --write  rewrites docs/architecture/dependency-graph.md in place.

Scans lib/features imports and reports:
  * feature -> feature edges (who imports whom, with file counts), split
    into domain-level (domain/ or application/ importer) vs
    presentation-level edges;
  * layer rule notes (domain must only touch other domains, never
    data/presentation/application of another feature).
"""

import re
import sys
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
FEATURES = ROOT / 'lib' / 'features'
DOC = ROOT / 'docs' / 'architecture' / 'dependency-graph.md'

IMPORT = re.compile(r"""^\s*import\s+['"]package:house_mira/features/([^/]+)/([^/]+)/""")
HEADER_WIDGET = 'package:house_mira/features/people/presentation/widgets/family_header_widget.dart'
DOMAIN_OR_APP = {'domain', 'application'}


def scan():
    edges: Counter[tuple[str, str, str]] = Counter()
    per_edge_files: dict[tuple[str, str, str], list[str]] = {}
    header_users: list[str] = []
    for path in sorted(FEATURES.rglob('*.dart')):
        rel = path.relative_to(FEATURES).parts
        if len(rel) < 3:
            continue
        src_feature, src_layer = rel[0], rel[1]
        try:
            text = path.read_text()
        except OSError:
            continue
        for line in text.splitlines():
            m = IMPORT.match(line)
            if not m:
                continue
            uri = line.split("'")[1] if "'" in line else line.split('"')[1]
            if uri == HEADER_WIDGET and src_feature != 'people':
                header_users.append('/'.join(rel))
            dst_feature, dst_layer = m.group(1), m.group(2)
            if dst_feature == src_feature:
                continue
            kind = (
                'domain'
                if src_layer in DOMAIN_OR_APP
                else 'presentation'
            )
            key = (src_feature, dst_feature, kind)
            edges[key] += 1
            per_edge_files.setdefault(key, []).append(
                f'{src_feature}/{"/".join(rel[1:])}',
            )
    return edges, per_edge_files, sorted(set(header_users))


def render(edges, per_edge_files, header_users) -> str:
    lines = [
        '# Feature dependency graph',
        '',
        '> Generated by `python3 tool/generate_dependency_graph.py --write`.',
        '> Do not hand-edit the edge lists below; fix the imports, re-run,',
        '> and commit the regenerated file.',
        '',
        'Direction: `A --> B` means a file in feature A imports a file',
        'from feature B. `domain` edges originate in `domain/` or',
        '`application/` (business logic); `presentation` edges originate',
        'in `presentation/` or the feature-local `data/` glue.',
        '',
        '```mermaid',
        'flowchart LR',
    ]
    for (src, dst, kind), count in sorted(edges.items()):
        style = '-.->' if kind == 'presentation' else '-->'
        lines.append(f'    {src} {style}|"{kind} x{count}"| {dst}')
    lines += ['```', '', '## Edges', '']
    if not edges:
        lines.append('_No cross-feature imports._')
    for (src, dst, kind), count in sorted(edges.items()):
        lines.append(f'### `{src}` → `{dst}` ({kind}, {count} imports)')
        lines.append('')
        for f in sorted(set(per_edge_files[(src, dst, kind)])):
            lines.append(f'- `{f}`')
        lines.append('')
    lines.append('## Target layering (ADR-0006)')
    lines.append('')
    lines += [
        '- `people` is the shared kernel: family/identity entities and',
        '  `PeopleRepository`. Other features depend on its **domain** only.',
        '- `reminders` exposes reminder entities + `ReminderRepository`;',
        '  `home` aggregates both into `HomeEntity` (domain-to-domain).',
        '- No feature imports another feature\'s `data/` (Supabase stays',
        '  behind the repository interface) or another feature\'s',
        '  `presentation/` widgets except the shared `FamilyHeaderWidget`',
        '  (explicit public UI surface, listed below until it moves to',
        '  `core/widgets/` in Phase 2).',
        '- Presentation cross-imports of `FamilyHeaderWidget`:',
    ]
    for f in header_users:
        lines.append(f'  - `{f}`')
    lines.append('')
    return '\n'.join(lines) + '\n'


def main() -> None:
    edges, per_edge_files, header_users = scan()
    doc = render(edges, per_edge_files, header_users)
    if '--write' in sys.argv:
        DOC.parent.mkdir(parents=True, exist_ok=True)
        DOC.write_text(doc)
        print(f'Wrote {DOC.relative_to(ROOT)}')
    else:
        print(doc)


if __name__ == '__main__':
    main()
