import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:vita_folder_mobile/core/auth/auth_service.dart';
import 'package:vita_folder_mobile/features/people/domain/repository/people_repository.dart';
import 'package:vita_folder_mobile/features/reminders/data/models/reminder_model.dart';
import 'package:vita_folder_mobile/features/reminders/domain/entities/reminder_type.dart';
import 'package:vita_folder_mobile/features/reminders/domain/usecase/create_reminder_usecase.dart';
import 'package:vita_folder_mobile/features/reminders/presentation/cubit/create_reminder_state.dart';

class CreateReminderCubit extends Cubit<CreateReminderState> {
  final CreateReminderUsecase _createReminderUsecase;
  final AuthService _authService;
  final PeopleRepository _peopleRepository;

  CreateReminderCubit({
    required CreateReminderUsecase createReminderUsecase,
    required AuthService authService,
    required PeopleRepository peopleRepository,
  })  : _createReminderUsecase = createReminderUsecase,
        _authService = authService,
        _peopleRepository = peopleRepository,
        super(CreateReminderInitial());

  Future<void> createReminder({
    required String title,
    required String body,
    required ReminderType type,
    required DateTime? dueDate,
    required String repeatRule,
  }) async {
    emit(CreateReminderLoading());

    final userId = _authService.currentUserId;
    if (userId.isEmpty) {
      emit(CreateReminderError(message: 'Authentication required'));
      return;
    }

    final reminder = ReminderModel(
      title: title,
      body: body,
      id: '', // ID will be generated by the backend
      type: type,
      dueDate: dueDate?.toIso8601String() ?? '',
      repeatRule: repeatRule,
      status: 'pending',
      createdBy: userId,
      createdAt: DateTime.now().toIso8601String(),
    );

    final familyIds = await _peopleRepository.getFamilyIdsForUser(userId);

    final result = await _createReminderUsecase(reminder, familyIds.isNotEmpty ? familyIds.first : '');

    result.fold(
      (err) => emit(CreateReminderError(message: err.message)),
      (_) => emit(CreateReminderSuccess()),
    );
  }
}