name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version-file: .fvmrc

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --profile

      - name: Upload to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: 1:140355243144:android:a6ac1f14183172f272633d
          serviceCredentialsFileContent: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          testers: ${{ secrets.FIREBASE_TESTERS }}
          file: build/app/outputs/flutter-apk/app-profile.apk
          releaseNotes: ${{ github.sha }}

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: apk-profile
          path: build/app/outputs/flutter-apk/*.apk
          retention-days: 3
