name: opencode-review-bob

on:
  workflow_call:
  
jobs:
  review:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      pull-requests: write
      issues: write
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: true
          token: ${{ secrets.GITHUB_TOKEN }}

      # Add these two steps to configure Git
      - name: Configure Git 
        run: |
          git config --global user.email "diogjp10@gmail.com"
          git config --global user.name "Diogo Action"   
      - uses: anomalyco/opencode/github@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          model: opencode/muse-spark-1.3-contributor-free
          use_github_token: true
          prompt: |
            Review the changes and give a grade from A to D. If the grade is A or B:
            - Aproove the PR and merge it. 
            - If C or D, comment with the suggestions. 
